### ISSUE TITLE
Bug when I try edit collection with abnormal "_id" field.

### ISSUE THREAD

**Issue by llevkin** [Kanatoko/MonjaDB#2]
i'm insert into collection document like this: 
db.collection.insert({"_id" : 1, "title":"lalal"});
db.collection.insert({"_id" : 2, "title":"lalal"});
..

After that, I can't edit this collection in MonjaDB.
"Document Editor" not display the object tree.
The fields in the table can't be edited.

All this happen if "_id" field is not a ObjectId...

Can you fix this bug? I'am very like MonjaDB, but this problem is impeding to work..(

P.s. Sorry for my bad English.)

**Comment by Kanatoko** [comment]
Thank you for your feedback.
I'll fix this.

**Comment by Kanatoko** [comment]
Fixed in 1.0.5.

**Comment by llevkin** [comment]
thank you!

**Comment by llevkin** [comment]
great tool=)

**Comment by Kanatoko** [comment]
:)

**Comment by llevkin** [comment]
Document Editor still don't work with abnormal _id fields.. do you fix it in other version?

**Comment by Kanatoko** [comment]
I think this issue is fixed in 1.0.5.
Please check your MonjaDBFeature Version is something like 1.0.5.2012...

**Comment by Kanatoko** [comment]
What is the type of your ObjectID? Double?

**Comment by llevkin** [comment]
No. NumberInt

**Comment by llevkin** [comment]
And when I edit JSON Object field with NumberInt fields inside, they all convert into Double after edit... Somthing like this: 
before edit: {id:1,type:'user',level:10}
after edit: {id:1.0,type:'user',level:10.0}

**Comment by llevkin** [comment]
version of MonjaDB is 1.0.5.201209292215

**Comment by Kanatoko** [comment]
Sorry I thought that your Object ID type is Double.
If NumberInt, it does not work on 1.0.5.

I'll fix this, but it will take some days. Please wait for a while.

**Comment by llevkin** [comment]
Thank you!

**Comment by Kanatoko** [comment]
1.0.6 is just released.  Now the DocumentEditor view works if the type of the ObjectID is NumberInt.

> And when I edit JSON Object field with NumberInt fields inside, they all convert into Double after edit...

It is design. If you want to preserve the type ( in this case, NumberInt ), use the DocumentEditor view, not JSON view.
I think the mongo shell is the same.

**Comment by llevkin** [comment]
Thank you! All work fine now! How is the best mongo gui tool! =)

**Comment by Kanatoko** [comment]
Thank you for the testing.
